# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55c27bd8bcfbecc7eb17f39a88acefdbf1a70d0b1e549c4bd77278f163e5788cbbf03821c6c8b247eed041b7cc9264be441c0f8d20829e2a25cf248becafdf3

test:
  secret_key_base: 414263b9e471d8ec9c5e918e6a3e40510864667f91dde03bc54c906f705d37c79302c9ca1466bbd5beb123e729b4ebd2e3527929c6734303e12ea07a3cece70e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
